# Generated by Django 5.2.4 on 2025-07-19 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('risk_level', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('active', 'Active'), ('pending', 'Pending')], max_length=50)),
                ('risks', models.ManyToManyField(related_name='nodes', to='supplychains.risk')),
            ],
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_description', models.CharField(max_length=255)),
                ('mode', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('cost', models.FloatField()),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('active', 'Active'), ('pending', 'Pending')], max_length=50)),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='supplychains.node')),
                ('to_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='supplychains.node')),
                ('risks', models.ManyToManyField(related_name='edges', to='supplychains.risk')),
            ],
        ),
    ]
