# Generated by Django 5.2.4 on 2025-07-19 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplychains', '0002_supplychain'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplychain',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
