# Generated by Django 5.2.4 on 2025-07-19 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplychains', '0003_supplychain_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='risk_score',
            field=models.FloatField(default=0.0),
        ),
    ]
