# Generated by Django 5.2.4 on 2025-07-21 19:01

import supplychains.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplychains', '0004_risk_risk_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='source',
            field=models.URLField(blank=True, null=True, validators=[supplychains.models.validate_https]),
        ),
    ]
