# Generated by Django 5.2.4 on 2025-07-21 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplychains', '0005_risk_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='type',
            field=models.CharField(choices=[('0', 'Geopolitical Risk'), ('1', 'Weather Risk'), ('2', 'Transport Disruption Risk'), ('3', 'Environmental Risk')], default='geopolitical', max_length=50),
        ),
    ]
