# Generated by Django 5.2.4 on 2025-07-22 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplychains', '0006_risk_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='risk',
            name='type',
        ),
        migrations.AddField(
            model_name='risk',
            name='risk_type',
            field=models.IntegerField(choices=[(0, 'Geopolitical Risk'), (1, 'Environmental Risk'), (2, 'Logistics Risk'), (3, 'Weather Risk')], default=0),
        ),
    ]
