# Generated by Django 5.2.4 on 2025-07-25 09:50

import supplychains.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplychains', '0007_remove_risk_type_risk_risk_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='url',
            field=models.URLField(blank=True, null=True, validators=[supplychains.models.validate_https]),
        ),
        migrations.AlterField(
            model_name='risk',
            name='source',
            field=models.CharField(blank=True, null=True),
        ),
    ]
