# Generated by Django 5.2.4 on 2025-10-10 21:20

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplychains', '0009_city_country_remove_node_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='risks',
        ),
        migrations.AlterField(
            model_name='node',
            name='city',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='country', chained_model_field='country', on_delete=django.db.models.deletion.PROTECT, to='supplychains.city'),
        ),
    ]
