# Generated by Django 5.2.4 on 2025-10-10 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplychains', '0010_remove_node_risks_alter_node_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='capacity_class',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='SUPPLIER', max_length=30),
        ),
        migrations.AddField(
            model_name='node',
            name='node_role',
            field=models.CharField(choices=[('SUPPLIER', 'Supplier'), ('MANUFACTURER', 'Manufacturer'), ('PLANT', 'Plant'), ('WAREHOUSE', 'Warehouse'), ('DISTRIBUTION_CENTER', 'Distribution Center'), ('PORT', 'Port'), ('AIRPORT', 'Airport'), ('CROSSDOCK', 'Crossdock'), ('CUSTOMER', 'Customer')], default='SUPPLIER', max_length=30),
        ),
        migrations.AddField(
            model_name='node',
            name='ownership',
            field=models.CharField(choices=[('INTERNAL', 'Internal'), ('3PL', 'Third Party Logistics'), ('SUPPLIER_OWNED', 'Supplier Owned'), ('JV', 'Joint Venture'), ('GOVERNMENT', 'Government')], default='SUPPLIER', max_length=30),
        ),
        migrations.AddField(
            model_name='node',
            name='transport_modes',
            field=models.CharField(choices=[('ROAD', 'Road'), ('RAIL', 'Rail'), ('AIR', 'Air'), ('SEA', 'Sea'), ('INLAND_WATERWAY', 'Inland Waterway')], default='SUPPLIER', max_length=30),
        ),
    ]
