# Generated by Django 5.2.4 on 2025-10-10 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplychains', '0011_node_capacity_class_node_node_role_node_ownership_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='risks',
            field=models.ManyToManyField(related_name='nodes', to='supplychains.risk'),
        ),
    ]
