# Generated by Django 5.2.4 on 2025-10-10 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplychains', '0012_node_risks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edge',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='status',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='time',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='transport_description',
        ),
        migrations.AddField(
            model_name='edge',
            name='crosses_border',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='SUPPLIER', max_length=30),
        ),
        migrations.AddField(
            model_name='edge',
            name='distance',
            field=models.CharField(choices=[('SHORT', 'Short'), ('MEDIUM', 'Medium'), ('LONG', 'Long')], default='SUPPLIER', max_length=30),
        ),
        migrations.AddField(
            model_name='edge',
            name='reliability',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='SUPPLIER', max_length=30),
        ),
        migrations.AddField(
            model_name='edge',
            name='transport_modes',
            field=models.CharField(choices=[('ROAD', 'Road'), ('RAIL', 'Rail'), ('AIR', 'Air'), ('SEA', 'Sea'), ('INLAND_WATERWAY', 'Inland Waterway')], default='SUPPLIER', max_length=30),
        ),
        migrations.AlterField(
            model_name='edge',
            name='cost',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='SUPPLIER', max_length=30),
        ),
    ]
