# Generated by Django 5.2.4 on 2025-10-10 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplychains', '0013_remove_edge_mode_remove_edge_status_remove_edge_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='risks',
            field=models.ManyToManyField(blank=True, related_name='edges', to='supplychains.risk'),
        ),
        migrations.AlterField(
            model_name='node',
            name='risks',
            field=models.ManyToManyField(blank=True, related_name='nodes', to='supplychains.risk'),
        ),
    ]
