# Generated by Django 5.2.4 on 2025-10-11 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplychains', '0014_alter_edge_risks_alter_node_risks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplychain',
            name='edges',
        ),
        migrations.RemoveField(
            model_name='supplychain',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='supplychain',
            name='nodes',
        ),
        migrations.AlterField(
            model_name='supplychain',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.CreateModel(
            name='ChainStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='supplychains.supplychain')),
                ('edge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chain_steps', to='supplychains.edge')),
            ],
            options={
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(fields=('chain', 'position'), name='uniq_chain_position')],
            },
        ),
    ]
