# Generated by Django 5.2.4 on 2025-10-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplychains', '0015_remove_supplychain_edges_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='edge',
            constraint=models.CheckConstraint(condition=models.Q(('from_node', models.F('to_node')), _negated=True), name='edge_no_self_loop'),
        ),
    ]
