# Generated by Django 5.2.4 on 2025-10-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplychains', '0016_edge_edge_no_self_loop'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplychain',
            name='supply_duration_days',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
