# Generated by Django 5.2.4 on 2025-10-11 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplychains', '0017_supplychain_supply_duration_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='transport_modes',
        ),
    ]
