# Generated by Django 5.2.4 on 2025-10-11 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplychains', '0018_remove_node_transport_modes'),
    ]

    operations = [
        migrations.AddField(
            model_name='edge',
            name='risk_score',
            field=models.FloatField(default=1.0, editable=False),
        ),
        migrations.AddField(
            model_name='node',
            name='delay_score',
            field=models.FloatField(default=1.0, editable=False),
        ),
    ]
