# Generated by Django 5.2.4 on 2025-10-11 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplychains', '0019_edge_risk_score_node_delay_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edge',
            old_name='risk_score',
            new_name='delay_score',
        ),
    ]
