# Generated by Django 5.2.4 on 2025-10-11 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplychains', '0020_rename_risk_score_edge_delay_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplychain',
            name='supply_duration_days',
        ),
    ]
