# Generated by Django 5.2.4 on 2025-10-11 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplychains', '0021_remove_supplychain_supply_duration_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='risk',
            name='risk_level',
        ),
        migrations.RemoveField(
            model_name='risk',
            name='risk_score',
        ),
    ]
