# Generated by Django 5.2.4 on 2025-10-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplychains', '0022_remove_risk_risk_level_remove_risk_risk_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplychain',
            name='predicted_delay',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
