# Generated by Django 5.2.4 on 2025-10-19 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplychains', '0023_supplychain_predicted_delay'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hold_type', models.CharField(choices=[('PRODUCTION', 'Production Hold'), ('TRANSPORT', 'Transport Hold'), ('INVENTORY', 'Inventory Hold'), ('ADMIN', 'Administrative Hold'), ('EXTERNAL', 'External / Environmental Hold')], default='PRODUCTION', help_text='Art des Hold-Ereignisses.', max_length=20)),
                ('severity', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, help_text='Schweregrad des Holds (1 = gering, 5 = kritisch).')),
                ('node', models.ForeignKey(help_text='Node, an dem der Hold auftritt.', on_delete=django.db.models.deletion.CASCADE, related_name='holds', to='supplychains.node')),
            ],
        ),
    ]
